### ISSUE TITLE
`.ok()` deviates from TestEZ api

### ISSUE THREAD

**Issue by 1enu** [goldenstein64/bustez#3]
`test.lua` has the following code:
```lua
expect(false).to.never.be.ok()
```
which contradicts roblox's implementation of `.ok()`
https://roblox.github.io/testez/api-reference/#expect

```lua
-- Nil checking
expect(1).to.be.ok()
expect(false).to.be.ok()
expect(nil).never.to.be.ok()
```

**Comment by goldenstein64** [comment]
I never knew it was an explicit `nil` check, just a truthy check... double-checking the source code, you're right.
